name: Run Gift Exchange

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Do a dry-run without sending SMS messages to the recipients."
        default: true
        type: boolean

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  test_run_script:
    name: Run xmas-change.py
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      id: aws-creds
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::157437238176:role/github-actions-xmas-xchange-role
        aws-region: ca-central-1

    - name: Generate .env
      run: |
        cat << EOF > .env
        TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }}
        TWILIO_PHONE_NUMBER=${{ secrets.TWILIO_PHONE_NUMBER }}
        AWS_ACCESS_KEY_ID=${{ steps.aws-creds.outputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY=${{ steps.aws-creds.outputs.aws-secret-access-key }}
        AWS_SESSION_TOKEN=${{ steps.aws-creds.outputs.aws-session-token }}
        AWS_REGION=ca-central-1
        S3_BUCKET=${{ secrets.S3_BUCKET }}
        EOF

    - name: Generate json/data.json
      run: echo "${{ secrets.DATA_JSON }}" | base64 -d > ./json/data.json

    - name: Build Docker Image
      run: docker build -t xmas-xchange .

    - name: Run Docker Image
      run: |
        if [ ${{ github.event.inputs.dryRun }} == true ]; then
          docker run --env-file .env --rm xmas-xchange --github-test
        else
          docker run --env-file .env --rm xmas-xchange
        fi