name: Run Gift Exchange

on:
  workflow_call:
    inputs:
      dryRun:
        description: "Do a dry-run without sending SMS messages to the recipients."
        default: true
        type: boolean

jobs:
  test_run_script:
    name: Run xmas-change.py
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Generate .env
      run: echo "${{ secrets.ENV }}" > .env

    - name: Generate json/data.json
      run: echo "${{ secrets.DATA_JSON }}" | base64 -d > ./json/data.json

    - name: Build Docker Image
      run: docker build -t xmas-xchange .

    - name: Run Docker Image
      run: |
        if [ ${{ github.event.inputs.dryRun }} == true ]; then
          docker run --rm xmas-xchange --github-test
        else
          docker run --rm xmas-xchange
        fi