name: Test Run Gift Exchange

on:
  pull_request:
    branches: [ "main" ]

jobs:
  run_script:
    name: Test run xmas-change.py
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Generate .env
      run: echo "${{ secrets.ENV }}" > .env

    - name: Generate json/data.json
      run: echo "${{ secrets.DATA_JSON }}" | base64 -d > ./json/data.json

    - name: Build Docker Image
      run: docker build -t xmas-xchange .

    - name: Run Docker Image
      run: docker run --env-file .env --rm xmas-xchange --github-test

    - name: Run test.py script with example data
      run: docker run --env-file .env --rm -v $(pwd)/json/data.example.json:/app/json/data.json --entrypoint python xmas-xchange test.py

    - name: Reminder to clean up test files
      run: echo "⚠️ Remember to manually clean up any github_*_dryrun.txt files from S3 as needed!"