name: Run Gift Exchange

on:
  pull_request:
    branches: [ "main" ]

jobs:
  run_script:
    name: Run xmas-change.py
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Generate .env
      run: echo "${{ secrets.ENV }}" > .env

    - name: Generate json/data.json
      run: echo "${{ secrets.DATA_JSON }}" > json/data.json

    - name: Build Docker Image
      run: docker build -t xmas-xchange .

    - name: Run Docker Image
      run: docker run --rm xmas-xchange --github-test